-- Fix schema for messaging/call/signaling flows
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS conversation_type VARCHAR(255);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS text TEXT;
ALTER TABLE calls ADD COLUMN IF NOT EXISTS call_id VARCHAR(255);
ALTER TABLE calls ADD COLUMN IF NOT EXISTS call_type VARCHAR(255);
ALTER TABLE calls ADD COLUMN IF NOT EXISTS caller_name VARCHAR(255);
ALTER TABLE calls ADD COLUMN IF NOT EXISTS recipient_name VARCHAR(255);
ALTER TABLE calls ADD COLUMN IF NOT EXISTS recipient_id VARCHAR(255);
ALTER TABLE calls ADD COLUMN IF NOT EXISTS answered_at TIMESTAMP;
ALTER TABLE call_notifications ADD COLUMN IF NOT EXISTS timestamp TIMESTAMP;
